---
label: Landing Page
name: landingPage
fields:
  - name: blocks
    label: Blocks
    type: blocks
    template_types:
      - message
      - diagram
pages:
  - content/marketing-pages/test_landing_page.md
